### PR TITLE
allow auth as an option for the client

### PR DESCRIPTION
**Pull request by karlkeefer**
Otherwise we'll have to change all of our helloblock calls to add in the auth key.

### CODE REVIEW

**Comment by taariq** [comment]
@sidazhang you okay to take a look so we can put this puppy in?

**Comment by karlkeefer** [comment]
@sidazhang how's this?

**Comment by sidazhang** [comment]
Thanks @karlkeefer

**Comment by sidazhang** [comment]
@karlkeefer I have published this as 0.2.5

https://github.com/helloblock/helloblock-js/commit/f9c1ca42ee54803af26d3d0bf7179aded8b6f888

**Comment by karlkeefer** [comment]
thanks @sidazhang!

**Pull request merged**
